name: Share job data
on: push
jobs:
  before:
    runs-on: ubuntu-slim
    steps:
      - id: generate
        run: echo "result=Hello" >> "{$GITHUB_OUTPUT}"
    outputs:
      result: ${{ steps.generate.outputs.result }}
  after:
    runs-on: ubuntu-slim
    needs: [before]
    steps:
      - env:
          RESULT: ${{ needs.before.outputs.result }}
        run: echo "${RESULT}"
